name: vmmr-eeg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - ipykernel
  - jupyterlab
  - notebook
  - matplotlib
  - seaborn
  - openpyxl
  - pip
  - pip:
    - xlrd
    - PyQt5==5.15.2
    - psychopy
    - pylsl